### ISSUE TITLE
Yarram gibi

### ISSUE THREAD

**Issue by fir4tozden** [ArviSlayer/V14-Slashli-Moderasyon-Sistemi#1]
Şu amina kodumun githubına bot atmayı kes aq discord botu devri mi kaldi amk

**Comment by ArviSlayer** [comment]
> Şu amina kodumun githubına bot atmayı kes aq discord botu devri mi kaldi amk

Öncelikle bu kaba tutumun için seni kınıyorum bre amına kodum O KADAR HAKLISIN ki. Artık insanların hayatını kolaylaştıracak projelere yönelme vakti
